### ISSUE TITLE
ContentType issue

### ISSUE THREAD

**Issue by flowl** [Jordan-Kowal/django_database_translation#2]
Hi, great project!
It didn't setup properbly tho.

In https://github.com/Jordan-Kowal/django-database-translation/blob/master/django_database_translation/models.py

```
    def get_content_type_instance(self):
        """Returns the ContentType instance of our object"""
        app = self._meta.app_label.lower()
        model = self.__class__.__name__.lower()
        content_type = ContentType.objects.get(app_label=app, model=model)
        return content_type
```

the `lower()` is causing problems and doesn't return any entries.

Example, My app: `Events` my model `Event`, they are not stored with lowercase, so the function doesn't return anything and throws error of missing ContentType.

**Comment by flowl** [comment]
```
sqlite> select * from django_content_type;
1|auth|permission
2|auth|group
3|contenttypes|contenttype
4|sessions|session
5|admin|logentry
6|Application|customuser
7|Events|event
8|thumbnail|kvstore
9|Events|participation
10|Events|voucher
11|Application|invoice
...
```

`app` is **not** lowercased, only the`model` name is.

**Comment by Jordan-Kowal** [comment]
Hey there, thanks for your feedback. It's been a while since I evne looked at this project though. I'll see what I can do

**Comment by Jordan-Kowal** [comment]
I ran some tests and you are correct. Django will automatically fill the `django_content_type` table using the `app.label` (which can be set in the AppConfig of your app) and the model name. Only the model name will be automatically lowercased.

I'll release a new version with that fix

**Comment by flowl** [comment]
Hey Jordan,
no worries. And while I'm typing this, you're already about to fix it, awesome!
Thanks a lot!

**Comment by Jordan-Kowal** [comment]
I'll make a new release ASAP with that fix. I just need to setup the github automatic pypi deployment first

**Comment by Jordan-Kowal** [comment]
I've release the `1.1.5` version on `pip`. 

Full disclaimer: I didnt check if there were other issues. I don't use this project anymore in my current work so I dont know how compatible it is with the newer Django versions. Since you already had identified the issue, I figured it wouldnt hurt to upload a quick fix. Let me know if it works.
